[solution]
name = "cutile-moe"               # Solution name
definition = "moe_fp8_block_scale_ds_routing_topk8_ng8_kg4_e32_h7168_i2048"
author = "aghilan"              # Team/author name

[build]
language = "python"               # python | triton | cuda
entry_point = "hardcoded.py::run" # file_path::function_name
source_dir = "cutile"             # cutile | torch | triton | cuda
